---
- name: Ensure Logstash SSL key pair directory exists.
  file:
    path: "{{ logstash_config_dir }}/ssl"
    state: directory
    mode: 0755

- name: Copy SSL key and cert for logstash-forwarder.
  copy:
    src: "ssl/{{ env }}/{{ item }}"
    dest: "{{ logstash_config_dir }}/ssl/{{ item | basename }}"
    mode: 0644
  with_items:
    - "{{ logstash_ssl_key_file }}"
    - "{{ logstash_ssl_certificate_file }}"
  notify: restart logstash


  
